BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = EEPROM SoftwareSerial DHT-sensor-library Adafruit_Sensor

USER_LIB_PATH = $(realpath ../lib)

AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk


