#!/bin/bash

#docker run --rm  --name influxdb   -p 8083:8083 -p 8086:8086 -p 25826:25826/udp   -v $PWD/influxdb/influxdb:/var/lib/influxdb   -v $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro   -v $PWD/influxdb/types.db:/usr/share/collectd/types.db:ro   influxdb:1.0

#docker run --rm  --name influxdb   -p 8083:8083 -p 8086:8086 -v $PWD/influxdb/influxdb:/var/lib/influxdb  influxdb:1.2


image=influxdb:1.3.3
if [ "$1" == "pi" ]; then
  echo "Image for armhs will be used, thanks to somsack..."
  image=somsakc/armhf-influxdb:1.2.4
fi

docker run --name emem_influxdb --rm -p 8086:8086 -p 8083:8083 -p 25826:25826/udp -v $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro -v $PWD/influxdb/var_lib_influxdb:/var/lib/influxdb  $image -config /etc/influxdb/influxdb.conf
