#!/bin/bash

#docker run --rm  --name influxdb   -p 8083:8083 -p 8086:8086 -p 25826:25826/udp   -v $PWD/influxdb/influxdb:/var/lib/influxdb   -v $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro   -v $PWD/influxdb/types.db:/usr/share/collectd/types.db:ro   influxdb:1.0

#docker run --rm  --name influxdb   -p 8083:8083 -p 8086:8086 -v $PWD/influxdb/influxdb:/var/lib/influxdb  influxdb:1.2
docker run --rm -p 8086:8086 -p 8083:8083 -v $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro -v $PWD/influxdb/var_lib_influxdb:/var/lib/influxdb  influxdb:1.3.3 -config /etc/influxdb/influxdb.conf
