#!/bin/bash

#EXAMPLE docker run --rm --name grafana   -p 3000:3000   -v $PWD/grafana/var:/var/lib/grafana -v $PWD/grafana/etc:/etc/grafana --link influxdb   grafana/grafana:3.1.1

image=grafana/grafana:4.4.3
if [ "$1" == "pi" ]; then
  echo "Image for armhs will be used, thanks to fg2it..."
  image=fg2it/grafana-armhf:v4.3.2
fi
docker run --rm --name emem_grafana   -p 3000:3000   -v $PWD/grafana/var_lib_grafana:/var/lib/grafana -v $PWD/grafana/etc_grafana:/etc/grafana --link emem_influxdb   $image


