BOARD_TAG   = nano328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = EEPROM SoftwareSerial DHT-sensor-library Adafruit_Sensor Low-Power btem thsem
AVRDUDE_ARD_BAUDRATE = 57600
ARDUINO_DIR  = /usr/share/arduino
USER_LIB_PATH = $(realpath ../lib)

include $(ARDUINO_DIR)/Arduino.mk




